#include <stdio.h>

#include "../include/common.h"
#include "../include/types.h"
#include "../include/dump.h"

COLD_REGION void help_print(char *argv[]) {
    printf("Usage: %s <input_file.vasm> <output_file.bin> <-flag>\n", argv[0]);
    printf("Flags:\n");
    printf("  -v, --vasm        Disassemble input file\n");
    printf("  -d, --debug       Dump generated bytecode in hex format\n");
    printf("  -l, --labels      Dump collected labels and their addresses\n");
    printf("  -s, --silent      Silent mode (no compilation output)\n");
    printf("  -D, --data        Dump .data section contents\n");
    printf("  -h, --help        Show this help message\n");
}

COLD_REGION void debug_hex(Assembler *asm_ctx) {
    printf("\nBytecode hex dump:\n");
    for (int i = 0; i < asm_ctx->bytecode_pos; i++) {
        printf("%02X ", asm_ctx->bytecode[i]);
        if ((i + 1) % 16 == 0) printf("\n");
    }
    printf("\n");
}

COLD_REGION void dump_labels(Assembler *asm_ctx) {
    printf("\nLabels found: %d\n", asm_ctx->label_count);
    printf("Code labels:\n");
    for (int i = 0; i < asm_ctx->label_count; i++) {
        if (!asm_ctx->labels[i].is_data)
            printf("  %s -> 0x%04X\n", asm_ctx->labels[i].name, asm_ctx->labels[i].address);
    }
    printf("Data labels:\n");
    for (int i = 0; i < asm_ctx->label_count; i++) {
        if (asm_ctx->labels[i].is_data)
            printf("  %s -> 0x%04X (data)\n", asm_ctx->labels[i].name, asm_ctx->labels[i].address);
    }
}

COLD_REGION void dump_data_section(Assembler *asm_ctx) {
    if (UNLIKELY(asm_ctx->data_pos == 0)) {
        printf("\nNo data section.\n");
        return;
    }

    printf("\nData section (%d bytes at 0x%04X):\n", asm_ctx->data_pos, asm_ctx->data_start_addr);

    for (int i = 0; i < asm_ctx->data_pos; i++) {
        if (i % 16 == 0)
            printf("%04X: ", asm_ctx->data_start_addr + i);

        printf("%02X ", asm_ctx->data_section[i]);

        if ((i + 1) % 16 == 0 || i == asm_ctx->data_pos - 1) {
            int start = (i / 16) * 16;
            int end = i + 1;
            printf(" | ");
            for (int j = start; j < end; j++) {
                char c = asm_ctx->data_section[j];
                printf("%c", (c >= 32 && c <= 126) ? c : '.');
            }
            printf("\n");
        }
    }
}